"""Info-Inhalt (Ueberblick, verwendete Modelle/Lizenzen) - wird als eigener
Abschnitt am Ende der Einstellungen-Seite angezeigt, siehe settings_page.py."""

from qt_app.constants import APP_NAME, APP_SUBTITLE, APP_VERSION

INFO_TEXT = (
    "═══════════════════════════════════════════════════════════\n"
    f"  {APP_NAME} {APP_SUBTITLE} — Übersicht\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "Diese Anwendung ermöglicht die lokale Aufnahme und automatische\n"
    "Transkription von Audio mit Sprechererkennung (Speaker Diarization).\n"
    "Alle Verarbeitungsschritte laufen vollständig lokal auf dem eigenen\n"
    "Rechner — es werden keine Audio-Daten an externe Server gesendet.\n\n"
    "─────────────────────────────────────────────────────────────\n"
    "  Funktionsumfang\n"
    "─────────────────────────────────────────────────────────────\n\n"
    "• Aufnahme von Mikrofon, System-Audio oder beidem gleichzeitig\n"
    "  (WASAPI Loopback unter Windows)\n"
    "• Automatische Transkription mit wortgenauem Zeitstempel-Alignment\n"
    "• Speaker Diarization — Erkennung und Zuordnung einzelner Sprecher\n"
    "• Sprecher-Umbenennung nach der Transkription\n"
    "• Export in TXT, SRT und JSON\n"
    "• GPU-Beschleunigung via CUDA (falls verfügbar)\n\n\n"
    "═══════════════════════════════════════════════════════════\n"
    "  Verwendete Modelle & Lizenzen\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  1. OpenAI Whisper (via WhisperX)                       │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Zweck:    Sprache-zu-Text Transkription                │\n"
    "│  Modelle:  large-v2, large-v3, medium, base             │\n"
    "│  Autor:    OpenAI                                       │\n"
    "│  Lizenz:   MIT License                                  │\n"
    "│  Quelle:   https://github.com/openai/whisper            │\n"
    "│                                                         │\n"
    "│  Hinweis: Die Whisper-Modelle stehen unter der MIT-     │\n"
    "│  Lizenz. Die Nutzung ist für kommerzielle und nicht-    │\n"
    "│  kommerzielle Zwecke gestattet.                         │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  2. WhisperX                                            │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Zweck:    Batched Inference, Forced Alignment,         │\n"
    "│            Integration der Diarization-Pipeline         │\n"
    "│  Autor:    Max Bain                                     │\n"
    "│  Lizenz:   BSD 4-Clause License                         │\n"
    "│  Quelle:   https://github.com/m-bain/whisperX           │\n"
    "│                                                         │\n"
    "│  Hinweis: WhisperX erweitert Whisper um wortgenaues     │\n"
    "│  Alignment und Speaker Diarization. BSD-4-Clause        │\n"
    "│  erfordert Namensnennung bei Weitergabe.                │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  3. pyannote.audio (Speaker Diarization)                │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Zweck:    Erkennung & Zuordnung von Sprechern          │\n"
    "│  Modell:   pyannote/speaker-diarization-3.1             │\n"
    "│  Autor:    Hervé Bredin (CNRS)                          │\n"
    "│  Lizenz:   MIT License                                  │\n"
    "│  Quelle:   https://github.com/pyannote/pyannote-audio   │\n"
    "│                                                         │\n"
    "│  ⚠ WICHTIG: Die Nutzung der pyannote-Modelle erfordert │\n"
    "│  die Zustimmung zu den Nutzungsbedingungen auf          │\n"
    "│  HuggingFace sowie einen gültigen HF-Token.            │\n"
    "│  Für kommerzielle Nutzung gelten ggf. separate          │\n"
    "│  Lizenzbedingungen — siehe pyannote.ai.                 │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  4. PyTorch                                             │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Zweck:    Deep-Learning-Framework für Inferenz         │\n"
    "│  Autor:    Meta AI (Facebook)                           │\n"
    "│  Lizenz:   BSD 3-Clause License                         │\n"
    "│  Quelle:   https://github.com/pytorch/pytorch           │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  5. Forced Alignment Modelle                            │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Zweck:    Wortgenaue Zeitstempel-Zuordnung             │\n"
    "│  Modelle:  WAV2VEC2-basierte Alignment-Modelle          │\n"
    "│            (sprachspezifisch, z.B. für DE, EN, FR)      │\n"
    "│  Autor:    Meta AI / HuggingFace Community              │\n"
    "│  Lizenz:   Apache 2.0 / MIT (modellabhängig)            │\n"
    "│  Quelle:   HuggingFace Model Hub                        │\n"
    "└─────────────────────────────────────────────────────────┘\n\n\n"
    "═══════════════════════════════════════════════════════════\n"
    "  Weitere Bibliotheken\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "• PySide6 (LGPLv3) — GUI-Framework\n"
    "• PyAudioWPatch (MIT) — Audio-Aufnahme unter Windows\n"
    "• SoundFile (BSD 3-Clause) — Audio-Datei I/O\n"
    "• SciPy (BSD 3-Clause) — Signal-Resampling\n"
    "• NumPy (BSD 3-Clause) — Numerische Berechnungen\n\n\n"
    "═══════════════════════════════════════════════════════════\n"
    "  Hinweise zur Nutzung\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "• Alle KI-Modelle werden beim ersten Start automatisch von\n"
    "  HuggingFace heruntergeladen und lokal zwischengespeichert.\n"
    "• Für Speaker Diarization wird ein kostenloser HuggingFace-\n"
    "  Account mit akzeptierten Modell-Bedingungen benötigt.\n"
    "• Die Transkriptionsqualität hängt von der Modellgröße ab:\n"
    "  large-v3 > large-v2 > medium > base (Qualität vs. Geschwindigkeit)\n"
    "• GPU (NVIDIA CUDA) wird empfohlen für large-Modelle.\n"
    "  CPU-Inferenz ist möglich, aber deutlich langsamer.\n\n"
    "─────────────────────────────────────────────────────────────\n"
    f"  {APP_NAME} v{APP_VERSION}\n"
    "  Alle Verarbeitung erfolgt lokal — keine Cloud-Dienste.\n"
    "─────────────────────────────────────────────────────────────\n"
)
