"""Info content (overview, models/licenses used) - shown as its own section
at the end of the Settings page, see settings_page.py."""

from qt_app.constants import APP_NAME, APP_VERSION

INFO_TEXT = (
    "═══════════════════════════════════════════════════════════\n"
    f"  {APP_NAME} — Overview\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "This application records audio locally and automatically\n"
    "transcribes it with speaker recognition (speaker diarization).\n"
    "Transcription uses your configured default provider (see\n"
    "Settings) if one is set up; if it's unreachable, the app\n"
    "automatically falls back to a local model. Recording and\n"
    "alignment/diarization always run locally on your own machine.\n\n"
    "Note: The first time a local model is actually needed (no\n"
    "provider configured, a provider request failed, or a local\n"
    "model was deliberately chosen), the app downloads it\n"
    "automatically from HuggingFace (about 1-3 GB, depending on the\n"
    "model). This can take a moment the very first time - after\n"
    "that, the model stays stored locally and isn't downloaded again.\n\n"
    "─────────────────────────────────────────────────────────────\n"
    "  Features\n"
    "─────────────────────────────────────────────────────────────\n\n"
    "• Record from microphone, system audio, or both at once\n"
    "  (WASAPI loopback on Windows)\n"
    "• Automatic transcription with word-accurate timestamp alignment\n"
    "• Speaker diarization — detecting and assigning individual speakers\n"
    "• Rename speakers after transcription\n"
    "• Export to TXT, SRT, and JSON\n"
    "• GPU acceleration via CUDA or Intel Arc GPU (if available)\n\n\n"
    "═══════════════════════════════════════════════════════════\n"
    "  Models used & licenses\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  1. OpenAI Whisper (via WhisperX)                       │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Purpose:  Speech-to-text transcription                 │\n"
    "│  Models:   large-v2, large-v3, medium, base              │\n"
    "│  Author:   OpenAI                                        │\n"
    "│  License:  MIT License                                   │\n"
    "│  Source:   https://github.com/openai/whisper             │\n"
    "│                                                          │\n"
    "│  Note: the Whisper models are released under the MIT     │\n"
    "│  license. Use is permitted for both commercial and       │\n"
    "│  non-commercial purposes.                                │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  2. WhisperX                                             │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Purpose:  Batched inference, forced alignment,          │\n"
    "│            diarization pipeline integration              │\n"
    "│  Author:   Max Bain                                      │\n"
    "│  License:  BSD 4-Clause License                          │\n"
    "│  Source:   https://github.com/m-bain/whisperX            │\n"
    "│                                                          │\n"
    "│  Note: WhisperX extends Whisper with word-accurate        │\n"
    "│  alignment and speaker diarization. BSD-4-Clause          │\n"
    "│  requires attribution on redistribution.                  │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  3. pyannote.audio (speaker diarization)                 │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Purpose:  Detecting & assigning speakers                │\n"
    "│  Model:    pyannote/speaker-diarization-3.1               │\n"
    "│  Author:   Hervé Bredin (CNRS)                            │\n"
    "│  License:  MIT License                                    │\n"
    "│  Source:   https://github.com/pyannote/pyannote-audio     │\n"
    "│                                                           │\n"
    "│  ⚠ IMPORTANT: using the pyannote models requires          │\n"
    "│  accepting their terms of use on HuggingFace and a         │\n"
    "│  valid HF token.                                           │\n"
    "│  Separate licensing terms may apply for commercial use     │\n"
    "│  — see pyannote.ai.                                        │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  4. PyTorch                                              │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Purpose:  Deep learning framework for inference          │\n"
    "│  Author:   Meta AI (Facebook)                             │\n"
    "│  License:  BSD 3-Clause License                           │\n"
    "│  Source:   https://github.com/pytorch/pytorch             │\n"
    "└─────────────────────────────────────────────────────────┘\n\n"
    "┌─────────────────────────────────────────────────────────┐\n"
    "│  5. Forced alignment models                              │\n"
    "├─────────────────────────────────────────────────────────┤\n"
    "│  Purpose:  Word-accurate timestamp alignment              │\n"
    "│  Models:   WAV2VEC2-based alignment models                │\n"
    "│            (language-specific, e.g. for DE, EN, FR)       │\n"
    "│  Author:   Meta AI / HuggingFace community                │\n"
    "│  License:  Apache 2.0 / MIT (model-dependent)              │\n"
    "│  Source:   HuggingFace Model Hub                          │\n"
    "└─────────────────────────────────────────────────────────┘\n\n\n"
    "═══════════════════════════════════════════════════════════\n"
    "  Other libraries\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "• PySide6 (LGPLv3) — GUI framework\n"
    "• PyAudioWPatch (MIT) — audio recording on Windows\n"
    "• SoundFile (BSD 3-Clause) — audio file I/O\n"
    "• SciPy (BSD 3-Clause) — signal resampling\n"
    "• NumPy (BSD 3-Clause) — numerical computation\n\n\n"
    "═══════════════════════════════════════════════════════════\n"
    "  Usage notes\n"
    "═══════════════════════════════════════════════════════════\n\n"
    "• Local AI models are downloaded automatically from HuggingFace\n"
    "  the first time they're needed and cached locally.\n"
    "• Speaker diarization requires a free HuggingFace account with\n"
    "  the model terms accepted.\n"
    "• Transcription quality depends on model size:\n"
    "  large-v3 > large-v2 > medium > base (quality vs. speed)\n"
    "• A GPU (NVIDIA CUDA or Intel Arc) is recommended for large models.\n"
    "  CPU inference is possible, but noticeably slower.\n\n"
    "─────────────────────────────────────────────────────────────\n"
    f"  {APP_NAME} v{APP_VERSION}\n"
    "  Recording and alignment/diarization always run locally;\n"
    "  transcription may use a configured remote provider.\n"
    "─────────────────────────────────────────────────────────────\n"
)
